# Generated by Django 4.0.5 on 2022-07-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('national_park_explorer', '0002_remove_customuser_favorites_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
    ]
